name: rfw_renderer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-203.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rfw: ^1.0.29
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
